### ISSUE TITLE
Empty sia space causing issues?

### ISSUE THREAD

**Issue by dim-geo** [YoRyan/sia-slice#3]
Hello,

I try to sync a big file to Sia via siaslice. (Sia 1.4.2)
Sia space is empty (no files). I think this causes issues during first sync...
Folder to upload exists, but empty.

```
python3.7 ./siaslice.py -m  -b 40 -t --debug /pics_bak/enc_partition.img backupdrive
```
```
[204] POST /renter/validatesiapath/backupdrive {}
[200] GET /renter/dir/backupdrive {}
Traceback (most recent call last):
  File "./siaslice.py", line 638, in <module>
    main()
  File "./siaslice.py", line 275, in main
    start(None)
  File "./siaslice.py", line 273, in start
    asyncio.run(amain(args, stdscr=stdscr))
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "./siaslice.py", line 290, in amain
    block_size=args.block*1000*1000, stdscr=stdscr)
  File "./siaslice.py", line 312, in do_mirror
    await storage.update()
  File "./siaslice.py", line 169, in update
    for siafile in siafiles:
TypeError: 'NoneType' object is not iterable
```

**Comment by YoRyan** [comment]
Apologies for the delay - and the bad code. I didn't get your exact traceback, but I did find a bug that affected initial uploads. Feel free to give it another try.
